/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sales_inv.view;
import com.sales_inv.model.InvoiceHeader;
import com.sales_inv.controller.InvoiceActionListener;
import com.sales_inv.model.InvoiceHeaderTableModel;
import com.sales_inv.model.InvoiceLine;

import com.sales_inv.controller.Table_sel_Listener;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Abdalla
 */
public class sales_invoice_frame extends javax.swing.JFrame {

    public static SimpleDateFormat getDateFormat() {
        return dateFormat;
    }

    public static void setDateFormat(SimpleDateFormat aDateFormat) {
        dateFormat = aDateFormat;
    }
    private ListSelectionListener selectionListener;

    /**
     * Creates new form sales_invoice_frame
     */
    public sales_invoice_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceHeadertable = new javax.swing.JTable();
        createnewinvoice = new javax.swing.JButton();
        deleteinvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customer_number = new javax.swing.JLabel();
        invoice_name = new javax.swing.JLabel();
        invoice_date = new javax.swing.JLabel();
        invoicetotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoice_line_table = new javax.swing.JTable();
        newline = new javax.swing.JButton();
        deleteline = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadfiles = new javax.swing.JMenuItem();
        savefiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceHeadertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvoiceHeadertable.getSelectionModel().addListSelectionListener(selectionListener);
        jScrollPane1.setViewportView(InvoiceHeadertable);

        createnewinvoice.addActionListener(actionListener);
        createnewinvoice.setText("create new invoice");
        createnewinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewinvoiceActionPerformed(evt);
            }
        });

        deleteinvoice.setText("delete invoice");
        deleteinvoice.addActionListener(actionListener);
        deleteinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteinvoiceActionPerformed(evt);
            }
        });

        jLabel1.setText("invoice num");

        jLabel2.setText("customer name");

        jLabel3.setText("invoice date");

        jLabel4.setText("invoice total");

        customer_number.setText("jLabel5");

        invoice_name.setText("jLabel6");

        invoice_date.setText("jLabel7");

        invoicetotal.setText("jLabel8");

        invoice_line_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(invoice_line_table);

        newline.setText("newline");
        newline.addActionListener(actionListener);
        newline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlineActionPerformed(evt);
            }
        });

        deleteline.setText("deleteline");
        deleteline.addActionListener(actionListener);
        deleteline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelineActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        loadfiles.setText("loadfiles");
        jMenu1.add(loadfiles);

        savefiles.setText("savefiles");
        savefiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savefilesActionPerformed(evt);
            }
        });
        jMenu1.add(savefiles);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(createnewinvoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteinvoice)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addComponent(newline)
                        .addGap(87, 87, 87)
                        .addComponent(deleteline)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoicetotal)
                                    .addComponent(invoice_date)
                                    .addComponent(invoice_name)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68)
                                .addComponent(customer_number)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(customer_number))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(invoice_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(invoice_date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invoicetotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteinvoice)
                    .addComponent(createnewinvoice)
                    .addComponent(newline)
                    .addComponent(deleteline))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savefilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savefilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savefilesActionPerformed

    private void createnewinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewinvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createnewinvoiceActionPerformed

    private void deleteinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteinvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteinvoiceActionPerformed

    private void newlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newlineActionPerformed

    private void deletelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletelineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales_invoice_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales_invoice_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales_invoice_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales_invoice_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales_invoice_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InvoiceHeadertable;
    private javax.swing.JButton createnewinvoice;
    private javax.swing.JLabel customer_number;
    private javax.swing.JButton deleteinvoice;
    private javax.swing.JButton deleteline;
    private javax.swing.JLabel invoice_date;
    private javax.swing.JTable invoice_line_table;
    private javax.swing.JLabel invoice_name;
    private javax.swing.JLabel invoicetotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadfiles;
    private javax.swing.JButton newline;
    private javax.swing.JMenuItem savefiles;
    // End of variables declaration//GEN-END:variables
private InvoiceActionListener actionListener = new InvoiceActionListener(this);
    private ArrayList<InvoiceHeader> invoicesArray;
    private ArrayList<InvoiceLine>Array_lines;
    private InvoiceHeaderTableModel headertableModel;
        private static SimpleDateFormat dateFormat= new SimpleDateFormat("dd-MM-yy");
        private Table_sel_Listener tableListener = new Table_sel_Listener(this);
        
         public ArrayList<InvoiceLine> getArray_lines() {
        return Array_lines;
    }

    public void setArray_lines(ArrayList<InvoiceLine> Array_lines) {
        this.Array_lines = Array_lines;
    }
        
        

    public ArrayList<InvoiceHeader> getInvoicesArray() {
        return invoicesArray;
    }


    public JTable getInvoice_Header_table() {
        return InvoiceHeadertable;
    }

    public JTable getInvoice_line_table() {
        return invoice_line_table;
    }

    public InvoiceHeaderTableModel getHeadertableModel() {
        return headertableModel;
    }

    public void setHeadertableModel(InvoiceHeaderTableModel headertableModel) {
        this.headertableModel = headertableModel;
    }

    public void setInvoicesArray(ArrayList<InvoiceHeader> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    public InvoiceHeader getInvObject(int code)
    {  for (InvoiceHeader inv :invoicesArray)
    {
        if (inv.getNum() == code)
        {
            return inv ; //  if it loops and find nothing in the invoice it will gives error 
        }
        return null ;
        
    }
        return null;
    }
    public JLabel getCustomer_name() {
        return customer_number;
    }

    public JLabel getInvoice_date() {
        return invoice_name;
    }

    public JLabel getInvoice_number() {
        
        return invoice_date;
    }

    public JLabel getInvoicetotal() {
        return invoicetotal;
    }

    public InvoiceActionListener getActionListener() {
        return actionListener;
    }


   
    
}
